# .travis.yml
# 指明使用的语言
language: "go"

root: "xenial"

os:
  - "linux"
go:          # 语言版本号
  - "1.13"   # 注意，需要 "1.10" 版本的时候必须表示为字符串形式，如果写成 1.10 则会使用 1.1 版本
  - "1.13.7"

script:      # 执行的脚步，但是go默认会执行下面的这些命令的，所以可以不用写
  - go test test/*.go -v
  - go build main.go