// Code generated by protoc-gen-go. DO NOT EDIT.
// source: BaseMessage.proto

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthReq struct {
	UnionId              string   `protobuf:"bytes,1,opt,name=union_id,json=unionId,proto3" json:"union_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthReq) Reset()         { *m = AuthReq{} }
func (m *AuthReq) String() string { return proto.CompactTextString(m) }
func (*AuthReq) ProtoMessage()    {}
func (*AuthReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed6ad4ef32f0d83c, []int{0}
}

func (m *AuthReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthReq.Unmarshal(m, b)
}
func (m *AuthReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthReq.Marshal(b, m, deterministic)
}
func (m *AuthReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthReq.Merge(m, src)
}
func (m *AuthReq) XXX_Size() int {
	return xxx_messageInfo_AuthReq.Size(m)
}
func (m *AuthReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthReq.DiscardUnknown(m)
}

var xxx_messageInfo_AuthReq proto.InternalMessageInfo

func (m *AuthReq) GetUnionId() string {
	if m != nil {
		return m.UnionId
	}
	return ""
}

type Response struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed6ad4ef32f0d83c, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Response) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type FuncReq struct {
	UnionId              string   `protobuf:"bytes,1,opt,name=union_id,json=unionId,proto3" json:"union_id,omitempty"`
	FuncName             string   `protobuf:"bytes,2,opt,name=func_name,json=funcName,proto3" json:"func_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FuncReq) Reset()         { *m = FuncReq{} }
func (m *FuncReq) String() string { return proto.CompactTextString(m) }
func (*FuncReq) ProtoMessage()    {}
func (*FuncReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed6ad4ef32f0d83c, []int{2}
}

func (m *FuncReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FuncReq.Unmarshal(m, b)
}
func (m *FuncReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FuncReq.Marshal(b, m, deterministic)
}
func (m *FuncReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FuncReq.Merge(m, src)
}
func (m *FuncReq) XXX_Size() int {
	return xxx_messageInfo_FuncReq.Size(m)
}
func (m *FuncReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FuncReq.DiscardUnknown(m)
}

var xxx_messageInfo_FuncReq proto.InternalMessageInfo

func (m *FuncReq) GetUnionId() string {
	if m != nil {
		return m.UnionId
	}
	return ""
}

func (m *FuncReq) GetFuncName() string {
	if m != nil {
		return m.FuncName
	}
	return ""
}

func init() {
	proto.RegisterType((*AuthReq)(nil), "protos.AuthReq")
	proto.RegisterType((*Response)(nil), "protos.Response")
	proto.RegisterType((*FuncReq)(nil), "protos.FuncReq")
}

func init() { proto.RegisterFile("BaseMessage.proto", fileDescriptor_ed6ad4ef32f0d83c) }

var fileDescriptor_ed6ad4ef32f0d83c = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x74, 0x4a, 0x2c, 0x4e,
	0xf5, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03,
	0x53, 0xc5, 0x4a, 0x2a, 0x5c, 0xec, 0x8e, 0xa5, 0x25, 0x19, 0x41, 0xa9, 0x85, 0x42, 0x92, 0x5c,
	0x1c, 0xa5, 0x79, 0x99, 0xf9, 0x79, 0xf1, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41,
	0xec, 0x60, 0xbe, 0x67, 0x8a, 0x92, 0x11, 0x17, 0x47, 0x50, 0x6a, 0x71, 0x41, 0x7e, 0x5e, 0x71,
	0xaa, 0x90, 0x10, 0x17, 0x4b, 0x49, 0x65, 0x41, 0x2a, 0x54, 0x09, 0x98, 0x0d, 0x12, 0x4b, 0x49,
	0x2c, 0x49, 0x94, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x09, 0x02, 0xb3, 0x95, 0x1c, 0xb9, 0xd8, 0xdd,
	0x4a, 0xf3, 0x92, 0xf1, 0x9b, 0x2c, 0x24, 0xcd, 0xc5, 0x99, 0x56, 0x9a, 0x97, 0x1c, 0x9f, 0x97,
	0x98, 0x9b, 0x0a, 0xd6, 0xce, 0x19, 0xc4, 0x01, 0x12, 0xf0, 0x4b, 0xcc, 0x4d, 0x35, 0x4a, 0xe2,
	0xe2, 0x02, 0x39, 0x2e, 0x38, 0xb5, 0xa8, 0x2c, 0xb5, 0x48, 0x48, 0x93, 0x8b, 0x05, 0xc4, 0x13,
	0xe2, 0x87, 0x78, 0xa1, 0x58, 0x0f, 0xea, 0x70, 0x29, 0x01, 0x98, 0x00, 0xdc, 0x8d, 0x9a, 0x5c,
	0x2c, 0x20, 0xbb, 0x11, 0x4a, 0xa1, 0x2e, 0xc1, 0x54, 0x9a, 0x04, 0x09, 0x08, 0x63, 0x40, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x64, 0x8e, 0xa6, 0x78, 0x24, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthServerClient is the client API for AuthServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServerClient interface {
	Auth(ctx context.Context, in *AuthReq, opts ...grpc.CallOption) (*Response, error)
	Func(ctx context.Context, in *FuncReq, opts ...grpc.CallOption) (*Response, error)
}

type authServerClient struct {
	cc *grpc.ClientConn
}

func NewAuthServerClient(cc *grpc.ClientConn) AuthServerClient {
	return &authServerClient{cc}
}

func (c *authServerClient) Auth(ctx context.Context, in *AuthReq, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/protos.AuthServer/Auth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServerClient) Func(ctx context.Context, in *FuncReq, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/protos.AuthServer/Func", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServerServer is the server API for AuthServer service.
type AuthServerServer interface {
	Auth(context.Context, *AuthReq) (*Response, error)
	Func(context.Context, *FuncReq) (*Response, error)
}

// UnimplementedAuthServerServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServerServer struct {
}

func (*UnimplementedAuthServerServer) Auth(ctx context.Context, req *AuthReq) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Auth not implemented")
}
func (*UnimplementedAuthServerServer) Func(ctx context.Context, req *FuncReq) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Func not implemented")
}

func RegisterAuthServerServer(s *grpc.Server, srv AuthServerServer) {
	s.RegisterService(&_AuthServer_serviceDesc, srv)
}

func _AuthServer_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServerServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.AuthServer/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServerServer).Auth(ctx, req.(*AuthReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthServer_Func_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FuncReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServerServer).Func(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.AuthServer/Func",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServerServer).Func(ctx, req.(*FuncReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.AuthServer",
	HandlerType: (*AuthServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Auth",
			Handler:    _AuthServer_Auth_Handler,
		},
		{
			MethodName: "Func",
			Handler:    _AuthServer_Func_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "BaseMessage.proto",
}
