// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package structs

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson8b3d011fDecodeUstbSsoStructs(in *jlexer.Lexer, out *State) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "state":
			out.State = int(in.Int())
		case "data":
			out.Data = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8b3d011fEncodeUstbSsoStructs(out *jwriter.Writer, in State) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"state\":"
		out.RawString(prefix[1:])
		out.Int(int(in.State))
	}
	{
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		out.String(string(in.Data))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v State) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8b3d011fEncodeUstbSsoStructs(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v State) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8b3d011fEncodeUstbSsoStructs(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *State) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8b3d011fDecodeUstbSsoStructs(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *State) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8b3d011fDecodeUstbSsoStructs(l, v)
}
func easyjson8b3d011fDecodeUstbSsoStructs1(in *jlexer.Lexer, out *AppToken) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = string(in.String())
		case "app_url":
			out.AppURL = string(in.String())
		case "appid":
			out.APPID = string(in.String())
		case "return_url":
			out.ReturnURL = string(in.String())
		case "rand_token":
			out.RandToken = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8b3d011fEncodeUstbSsoStructs1(out *jwriter.Writer, in AppToken) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"app_url\":"
		out.RawString(prefix)
		out.String(string(in.AppURL))
	}
	{
		const prefix string = ",\"appid\":"
		out.RawString(prefix)
		out.String(string(in.APPID))
	}
	{
		const prefix string = ",\"return_url\":"
		out.RawString(prefix)
		out.String(string(in.ReturnURL))
	}
	{
		const prefix string = ",\"rand_token\":"
		out.RawString(prefix)
		out.String(string(in.RandToken))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AppToken) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8b3d011fEncodeUstbSsoStructs1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AppToken) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8b3d011fEncodeUstbSsoStructs1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AppToken) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8b3d011fDecodeUstbSsoStructs1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AppToken) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8b3d011fDecodeUstbSsoStructs1(l, v)
}
